cache = true
max_cache_age = "7d"
timeout = 20
max_concurrency = 8
max_redirects = 5
accept = [200, 202, 206, 304]

exclude_path = [
  "node_modules",
  "dist",
  "build",
  "coverage",
]

exclude = [
  "^https?://localhost(:[0-9]+)?",
  "^https?://127\\.0\\.0\\.1(:[0-9]+)?",
]

include_fragments = false
